name: Build
run-name: ${{ github.actor }} is building ${{github.action_repository}}
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      - run: yarn
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build